spring:
  datasource:
    url: "jdbc:mysql://localhost/library"
    username: "root"
    password: "ahslxj2429"
    driver-class-name: com.mysql.cj.jdbc.Driver

    application:
      properties:"http://localhost:3000"